### ISSUE TITLE
Confusing semantics w/ `first`

### ISSUE THREAD

**Issue by eigenhombre** [pytoolz/toolz#247]
`first([])` throws `StopIteration`.  I expected it to return `None`, contaminated as I am by everything Clojure (`(first [])` yields `nil`).

In underscore.js, `_.first([])` returns `undefined`, which is pretty much what I'd expect.

@mrocklin thoughts?

**Comment by mrocklin** [comment]
Would there be a difference between the following:

```python
>>> first([])
>>> first([None])
```

**Comment by eigenhombre** [comment]
No difference in the return values, nope.  In my experience the second case is vastly more rare than the first.

**Comment by eriknw** [comment]
I understand where you're coming from.  However, Clojure's `nil` is very different from Python's `None`, and `toolz` aims to be pythonic.  In a script, I would want `first` (and `second`, `nth`, and `last`) to raise an error if the sequence is too short, because I don't want to fail silently or to interpret `None` as a failure.  In a REPL, I would usually prefer the behavior you propose, but I also don't care if I raise an exception in a REPL.

If Python had a single value to specify that an item doesn't exist, I would suggest we use it.  `None` is not this value.  Python actually has several such values, and they are in the form of exceptions: `StopIteration`, `IndexError`, `KeyError`, `AttributeError`, etc.

**Comment by llllllllll** [comment]
As prior art to the the exception, haskell's `head` function raises on an empty list

**Comment by eriknw** [comment]
Good point, @llllllllll.

I would like to close this issue.  Does anybody disagree?

The confusion seems to be more generally from coming from Clojure to Python, where missing values are handled very differently.  That said, I do like the Clojure style, so it may be worth exploring defining a `Nil` singleton in `toolz`.

**Comment by eriknw** [comment]
This behavior is not likely to change in `toolz`.  Closing.

**Comment by eigenhombre** [comment]
Just out of curiosity, @eriknw, "Clojure's nil is very different from None."  How do you see them being different?
