### ISSUE TITLE
pluck won't accept tuple of indexes

### ISSUE THREAD

**Issue by ghost** [pytoolz/toolz#279]
Although the docs say "`ind` can be either a single string/index or a sequence of strings/indices.",
I've had no luck with tuples:

Python 3.4.2 (default, Nov 30 2014, 16:46:39) 
In [1]: import toolz
In [2]: dicts = [{'k1': 'v1'},{'k1': 'v2'}]
In [3]: keys = ('k1',)
In [4]: list(toolz.pluck(keys, dicts))

KeyError                                  Traceback (most recent call last)
<ipython-input-4-71ca2c465d1a> in <module>()
----> 1 list(toolz.pluck(keys, dicts))

KeyError: ('k1',)

In [5]: list(toolz.pluck(list(keys), dicts))  
Out[5]: [('v1',), ('v2',)]

**Comment by Digenis** [comment]
Indeed, https://github.com/pytoolz/toolz/blob/53146dc42359fa1a3e479856f0c400d2ed4e883f/toolz/itertoolz.py#L726

Probably, either the documentation or code will be fixed.

From my perspective, they are both wrong.
I'd expect `ind` to  be passed directly to the `__getitem__` method
of each element of the sequence.

I think no simple solution works because:

Say, the code gets fixed to check for tuple instances,
pluck won't work for dictionaries whose keys are tuples.

Say, the documentation gets fixed to state that only lists behave like this,
pluck won't work for dictionary subclasses that define a custom `__hash__` method
that enable them to work with lists.

You can substitute words above,
like `dictionary` with `MutableMapping`
and `list` with `MutableSequence`
just to make the problem look wider.

I think it could be much simpler if `ind` was restricted to a single type.
So rather change the doc to: *`ind` must be a sequence of indices*
and remove 2 lines to implement it as such.
Now, if someone wants to pluck a single index/key
it costs nothing to pass it wrapped in `[]`.
E.g. `pluck(key, seqs)` will need to become `pluck([key], seqs)`

But you can disregard all the above.
It haven't occurred to me to actually use `pluck`
but I thought my comment can be somehow constructive.

**Comment by mrocklin** [comment]
You are correct that we should change something.  I think that we should change the documentation to specify that only lists will pick out multiple elements.  

I'm not overly concerned about classes that override `__hash__`.  Toolz is optimized for core data structures.

**Comment by eriknw** [comment]
Hi Jason!

Thank you for the careful reading.  This is indeed an issue with the docstring of `pluck`.  It should read `"or a list of"`, not `"or a sequence of"`.  `get` clearly states a list is expected, and `pluck` should too.

@Digenis, your point is well taken.  The convention of using a single index or a *list* of indices is used several places in `toolz`, and is a convenience that I wish to keep.

**Comment by eriknw** [comment]
The docstring has been updated to say list, not sequence.
