### ISSUE TITLE
builds are failing on master

### ISSUE THREAD

**Issue by diwu1989** [pytoolz/toolz#296]
pretty scary to see master having failed builds

**Comment by mrocklin** [comment]
It looks like the badge is just incorrectly set up to fail if PRs are failing.  

I believe that master is fine.

**Comment by eriknw** [comment]
Aha, the badge is failing because it is not referencing the master branch.

https://api.travis-ci.org/pytoolz/toolz.svg
![current](https://api.travis-ci.org/pytoolz/toolz.svg)
was referencing
https://api.travis-ci.org/pytoolz/toolz.svg?branch=0.7.4
![current](https://api.travis-ci.org/pytoolz/toolz.svg?branch=0.7.4)
instead of
https://api.travis-ci.org/pytoolz/toolz.svg?branch=master
![master](https://api.travis-ci.org/pytoolz/toolz.svg?branch=master)

**Comment by eriknw** [comment]
The TravisCI badge has been updated.  I'll check the other badges.

Thanks @diwu1989

**Comment by eriknw** [comment]
Also, note that 0.7.4 branch was failing due to `pip install coverage` no longer works for Python 3.2.  We have removed Python 3.2 from the test matrix.
