### ISSUE TITLE
when is the latest version going to be published?

### ISSUE THREAD

**Issue by kindjacket** [pytoolz/toolz#441]

**Comment by eriknw** [comment]
This is on my very short list of things to do.  My bad.  If it's any consolation, I've been behind on lots of things!

Thanks for caring enough to create an issue.  That does mean a lot to me.

**Comment by yozlet** [comment]
@eriknw Does the pytoolz org have other maintainers who can help you out here? Are there more who could be recruited? Alternatively, moving toolz to [Jazzband](https://jazzband.co/) or similar collaborative community might ease much of the load. (They have folks who are happy to join threads like this and offer advice/help, too.)

**Comment by yozlet** [comment]
To be clear, none of my comment above is any kind of criticism! I'm brand new to toolz and seeing a bunch of waiting PRs that I'd like to use (especially #398). I'm also someone who often has _far_ too much on my plate, and I tend to forget that there are others available who are willing to help with certain things. Toolz is an awesome project, I'd love to see it thrive.

**Comment by eriknw** [comment]
Released 0.10.0 to PyPI!

Thanks for the interest and patience.  Jazzband is new to me, so I'll check it out.  I was unusually busy in "real life" since the previous release, and I expect I'll be able to be more responsive now and in the future (although I'm still playing catch up on some issues and PRs).
